[2025-05-03T19:19:58.638+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T19:19:58.680+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-29T02:30:00+00:00 [queued]>
[2025-05-03T19:19:58.706+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-29T02:30:00+00:00 [queued]>
[2025-05-03T19:19:58.710+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-03T19:19:59.004+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_sentiment_data_to_snowflake> on 2025-04-29 02:30:00+00:00
[2025-05-03T19:19:59.043+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-03T19:19:59.057+0000] {standard_task_runner.py:72} INFO - Started process 262 to run task
[2025-05-03T19:19:59.050+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_final_etl', 'load_sentiment_data_to_snowflake', 'scheduled__2025-04-29T02:30:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl.py', '--cfg-path', '/tmp/tmpexmy1aao']
[2025-05-03T19:19:59.062+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask load_sentiment_data_to_snowflake
[2025-05-03T19:19:59.176+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-29T02:30:00+00:00 [running]> on host 4d9a18829078
[2025-05-03T19:19:59.395+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_final_etl' AIRFLOW_CTX_TASK_ID='load_sentiment_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T02:30:00+00:00'
[2025-05-03T19:19:59.401+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-03T19:19:59.436+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-03T19:19:59.439+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-05-03T19:19:59.441+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-03T19:19:59.443+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-03T19:20:01.505+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-03T19:20:01.953+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
