[2025-05-07T00:43:58.097+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-07T00:43:58.117+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2025-05-07T00:43:33.279098+00:00 [queued]>
[2025-05-07T00:43:58.127+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2025-05-07T00:43:33.279098+00:00 [queued]>
[2025-05-07T00:43:58.129+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-07T00:43:58.144+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-05-07 00:43:33.279098+00:00
[2025-05-07T00:43:58.152+0000] {standard_task_runner.py:72} INFO - Started process 1109 to run task
[2025-05-07T00:43:58.155+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2025-05-07T00:43:33.279098+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpoepdfjwi']
[2025-05-07T00:43:58.157+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask dbt_test
[2025-05-07T00:43:58.202+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2025-05-07T00:43:33.279098+00:00 [running]> on host 55fd2231a72d
[2025-05-07T00:43:58.294+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T00:43:33.279098+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T00:43:33.279098+00:00'
[2025-05-07T00:43:58.296+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-07T00:43:58.312+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-07T00:43:58.315+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/tesla_project --project-dir /opt/***/tesla_project']
[2025-05-07T00:43:58.327+0000] {subprocess.py:86} INFO - Output:
[2025-05-07T00:44:00.677+0000] {subprocess.py:93} INFO - [0m00:44:00  Running with dbt=1.8.7
[2025-05-07T00:44:01.673+0000] {subprocess.py:93} INFO - [0m00:44:01  Registered adapter: snowflake=1.8.1
[2025-05-07T00:44:02.169+0000] {subprocess.py:93} INFO - [0m00:44:02  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-05-07T00:44:02.171+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-05-07T00:44:02.172+0000] {subprocess.py:93} INFO - - models.tesla_project.example
[2025-05-07T00:44:02.422+0000] {subprocess.py:93} INFO - [0m00:44:02  Found 3 models, 1 snapshot, 1 seed, 1 source, 459 macros
[2025-05-07T00:44:02.426+0000] {subprocess.py:93} INFO - [0m00:44:02
[2025-05-07T00:44:02.428+0000] {subprocess.py:93} INFO - [0m00:44:02  Nothing to do. Try checking your model configs and model specification args
[2025-05-07T00:44:03.161+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-07T00:44:03.192+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-07T00:44:03.194+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2025-05-07T00:43:33.279098+00:00, execution_date=20250507T004333, start_date=20250507T004358, end_date=20250507T004403
[2025-05-07T00:44:03.238+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-07T00:44:03.260+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-07T00:44:03.265+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
