[2025-05-07T00:43:36.317+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-07T00:43:36.347+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-07T00:43:33.279098+00:00 [queued]>
[2025-05-07T00:43:36.385+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-07T00:43:33.279098+00:00 [queued]>
[2025-05-07T00:43:36.386+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-07T00:43:36.403+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2025-05-07 00:43:33.279098+00:00
[2025-05-07T00:43:36.415+0000] {standard_task_runner.py:72} INFO - Started process 1045 to run task
[2025-05-07T00:43:36.418+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2025-05-07T00:43:33.279098+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp_5ojojol']
[2025-05-07T00:43:36.422+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask dbt_run
[2025-05-07T00:43:36.476+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-07T00:43:33.279098+00:00 [running]> on host 55fd2231a72d
[2025-05-07T00:43:36.614+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T00:43:33.279098+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T00:43:33.279098+00:00'
[2025-05-07T00:43:36.616+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-07T00:43:36.665+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-07T00:43:36.673+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/tesla_project --project-dir /opt/***/tesla_project']
[2025-05-07T00:43:36.691+0000] {subprocess.py:86} INFO - Output:
[2025-05-07T00:43:41.066+0000] {subprocess.py:93} INFO - [0m00:43:41  Running with dbt=1.8.7
[2025-05-07T00:43:45.177+0000] {subprocess.py:93} INFO - [0m00:43:45  Registered adapter: snowflake=1.8.1
[2025-05-07T00:43:45.681+0000] {subprocess.py:93} INFO - [0m00:43:45  Unable to do partial parsing because of a version mismatch
[2025-05-07T00:43:47.969+0000] {subprocess.py:93} INFO - [0m00:43:47  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-05-07T00:43:47.970+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-05-07T00:43:47.971+0000] {subprocess.py:93} INFO - - models.tesla_project.example
[2025-05-07T00:43:48.194+0000] {subprocess.py:93} INFO - [0m00:43:48  Found 3 models, 1 snapshot, 1 seed, 1 source, 459 macros
[2025-05-07T00:43:48.197+0000] {subprocess.py:93} INFO - [0m00:43:48
[2025-05-07T00:43:50.542+0000] {subprocess.py:93} INFO - [0m00:43:50  Concurrency: 1 threads (target='dev')
[2025-05-07T00:43:50.543+0000] {subprocess.py:93} INFO - [0m00:43:50
[2025-05-07T00:43:50.607+0000] {subprocess.py:93} INFO - [0m00:43:50  1 of 3 START sql table model analytics.input ................................... [RUN]
[2025-05-07T00:43:52.022+0000] {subprocess.py:93} INFO - [0m00:43:52  1 of 3 OK created sql table model analytics.input .............................. [[32mSUCCESS 1[0m in 1.41s]
[2025-05-07T00:43:52.026+0000] {subprocess.py:93} INFO - [0m00:43:52  2 of 3 START sql table model analytics.sentiment_features_final ................ [RUN]
[2025-05-07T00:43:54.195+0000] {subprocess.py:93} INFO - [0m00:43:54  2 of 3 OK created sql table model analytics.sentiment_features_final ........... [[32mSUCCESS 1[0m in 2.17s]
[2025-05-07T00:43:54.200+0000] {subprocess.py:93} INFO - [0m00:43:54  3 of 3 START sql table model analytics.output .................................. [RUN]
[2025-05-07T00:43:56.321+0000] {subprocess.py:93} INFO - [0m00:43:56  3 of 3 OK created sql table model analytics.output ............................. [[32mSUCCESS 1[0m in 2.12s]
[2025-05-07T00:43:56.327+0000] {subprocess.py:93} INFO - [0m00:43:56
[2025-05-07T00:43:56.328+0000] {subprocess.py:93} INFO - [0m00:43:56  Finished running 3 table models in 0 hours 0 minutes and 8.13 seconds (8.13s).
[2025-05-07T00:43:56.481+0000] {subprocess.py:93} INFO - [0m00:43:56
[2025-05-07T00:43:56.482+0000] {subprocess.py:93} INFO - [0m00:43:56  [32mCompleted successfully[0m
[2025-05-07T00:43:56.484+0000] {subprocess.py:93} INFO - [0m00:43:56
[2025-05-07T00:43:56.485+0000] {subprocess.py:93} INFO - [0m00:43:56  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2025-05-07T00:43:57.163+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-07T00:43:57.196+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-07T00:43:57.198+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2025-05-07T00:43:33.279098+00:00, execution_date=20250507T004333, start_date=20250507T004336, end_date=20250507T004357
[2025-05-07T00:43:57.261+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-07T00:43:57.299+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-07T00:43:57.303+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
