[2025-05-07T00:43:36.317+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-07T00:43:36.347+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_seed manual__2025-05-07T00:43:33.279098+00:00 [queued]>
[2025-05-07T00:43:36.367+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_seed manual__2025-05-07T00:43:33.279098+00:00 [queued]>
[2025-05-07T00:43:36.369+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-07T00:43:36.394+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_seed> on 2025-05-07 00:43:33.279098+00:00
[2025-05-07T00:43:36.404+0000] {standard_task_runner.py:72} INFO - Started process 1043 to run task
[2025-05-07T00:43:36.408+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_seed', 'manual__2025-05-07T00:43:33.279098+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp5fqmp5t5']
[2025-05-07T00:43:36.412+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask dbt_seed
[2025-05-07T00:43:36.469+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_seed manual__2025-05-07T00:43:33.279098+00:00 [running]> on host 55fd2231a72d
[2025-05-07T00:43:36.613+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_seed' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T00:43:33.279098+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T00:43:33.279098+00:00'
[2025-05-07T00:43:36.616+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-07T00:43:36.665+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-07T00:43:36.674+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/tesla_project --project-dir /opt/***/tesla_project']
[2025-05-07T00:43:36.691+0000] {subprocess.py:86} INFO - Output:
[2025-05-07T00:43:41.068+0000] {subprocess.py:93} INFO - [0m00:43:41  Running with dbt=1.8.7
[2025-05-07T00:43:45.178+0000] {subprocess.py:93} INFO - [0m00:43:45  Registered adapter: snowflake=1.8.1
[2025-05-07T00:43:45.666+0000] {subprocess.py:93} INFO - [0m00:43:45  Unable to do partial parsing because of a version mismatch
[2025-05-07T00:43:47.976+0000] {subprocess.py:93} INFO - [0m00:43:47  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-05-07T00:43:47.978+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-05-07T00:43:47.978+0000] {subprocess.py:93} INFO - - models.tesla_project.example
[2025-05-07T00:43:48.193+0000] {subprocess.py:93} INFO - [0m00:43:48  Found 3 models, 1 snapshot, 1 seed, 1 source, 459 macros
[2025-05-07T00:43:48.197+0000] {subprocess.py:93} INFO - [0m00:43:48
[2025-05-07T00:43:51.074+0000] {subprocess.py:93} INFO - [0m00:43:51  Concurrency: 1 threads (target='dev')
[2025-05-07T00:43:51.075+0000] {subprocess.py:93} INFO - [0m00:43:51
[2025-05-07T00:43:51.087+0000] {subprocess.py:93} INFO - [0m00:43:51  1 of 3 START sql table model analytics.input ................................... [RUN]
[2025-05-07T00:43:54.237+0000] {subprocess.py:93} INFO - [0m00:43:54  1 of 3 OK created sql table model analytics.input .............................. [[32mSUCCESS 1[0m in 3.15s]
[2025-05-07T00:43:54.241+0000] {subprocess.py:93} INFO - [0m00:43:54  2 of 3 START sql table model analytics.sentiment_features_final ................ [RUN]
[2025-05-07T00:43:56.444+0000] {subprocess.py:93} INFO - [0m00:43:56  2 of 3 OK created sql table model analytics.sentiment_features_final ........... [[32mSUCCESS 1[0m in 2.20s]
[2025-05-07T00:43:56.447+0000] {subprocess.py:93} INFO - [0m00:43:56  3 of 3 START sql table model analytics.output .................................. [RUN]
[2025-05-07T00:43:58.205+0000] {subprocess.py:93} INFO - [0m00:43:58  3 of 3 OK created sql table model analytics.output ............................. [[32mSUCCESS 1[0m in 1.75s]
[2025-05-07T00:43:58.211+0000] {subprocess.py:93} INFO - [0m00:43:58
[2025-05-07T00:43:58.212+0000] {subprocess.py:93} INFO - [0m00:43:58  Finished running 3 table models in 0 hours 0 minutes and 10.01 seconds (10.01s).
[2025-05-07T00:43:58.376+0000] {subprocess.py:93} INFO - [0m00:43:58
[2025-05-07T00:43:58.378+0000] {subprocess.py:93} INFO - [0m00:43:58  [32mCompleted successfully[0m
[2025-05-07T00:43:58.379+0000] {subprocess.py:93} INFO - [0m00:43:58
[2025-05-07T00:43:58.380+0000] {subprocess.py:93} INFO - [0m00:43:58  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2025-05-07T00:43:59.087+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-07T00:43:59.112+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-07T00:43:59.114+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_seed, run_id=manual__2025-05-07T00:43:33.279098+00:00, execution_date=20250507T004333, start_date=20250507T004336, end_date=20250507T004359
[2025-05-07T00:43:59.151+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-07T00:43:59.166+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-07T00:43:59.169+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
