[2025-05-06T03:57:54.553+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T03:57:54.578+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-06T03:57:53.262913+00:00 [queued]>
[2025-05-06T03:57:54.590+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-06T03:57:53.262913+00:00 [queued]>
[2025-05-06T03:57:54.591+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-06T03:57:54.610+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2025-05-06 03:57:53.262913+00:00
[2025-05-06T03:57:54.626+0000] {standard_task_runner.py:72} INFO - Started process 3049 to run task
[2025-05-06T03:57:54.631+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2025-05-06T03:57:53.262913+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp4iyocq5j']
[2025-05-06T03:57:54.638+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask dbt_run
[2025-05-06T03:57:54.707+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-06T03:57:53.262913+00:00 [running]> on host 4bf74f6ca137
[2025-05-06T03:57:54.790+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T03:57:53.262913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T03:57:53.262913+00:00'
[2025-05-06T03:57:54.792+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-06T03:57:54.807+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T03:57:54.811+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/tesla_project --project-dir /opt/***/tesla_project']
[2025-05-06T03:57:54.827+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T03:57:57.205+0000] {subprocess.py:93} INFO - [0m03:57:57  Running with dbt=1.8.7
[2025-05-06T03:57:58.264+0000] {subprocess.py:93} INFO - [0m03:57:58  Registered adapter: snowflake=1.8.1
[2025-05-06T03:57:58.553+0000] {subprocess.py:93} INFO - [0m03:57:58  Unable to do partial parsing because a project config has changed
[2025-05-06T03:58:00.477+0000] {subprocess.py:93} INFO - [0m03:58:00  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-05-06T03:58:00.479+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-05-06T03:58:00.480+0000] {subprocess.py:93} INFO - - models.tesla_project.example
[2025-05-06T03:58:00.729+0000] {subprocess.py:93} INFO - [0m03:58:00  Found 3 models, 1 snapshot, 1 source, 459 macros
[2025-05-06T03:58:00.736+0000] {subprocess.py:93} INFO - [0m03:58:00
[2025-05-06T03:58:06.168+0000] {subprocess.py:93} INFO - [0m03:58:06  Concurrency: 1 threads (target='dev')
[2025-05-06T03:58:06.173+0000] {subprocess.py:93} INFO - [0m03:58:06
[2025-05-06T03:58:06.210+0000] {subprocess.py:93} INFO - [0m03:58:06  1 of 3 START sql table model analytics.input ................................... [RUN]
[2025-05-06T03:58:09.346+0000] {subprocess.py:93} INFO - [0m03:58:09  1 of 3 OK created sql table model analytics.input .............................. [[32mSUCCESS 1[0m in 3.12s]
[2025-05-06T03:58:09.360+0000] {subprocess.py:93} INFO - [0m03:58:09  2 of 3 START sql table model analytics.sentiment_features_final ................ [RUN]
[2025-05-06T03:58:12.728+0000] {subprocess.py:93} INFO - [0m03:58:12  2 of 3 OK created sql table model analytics.sentiment_features_final ........... [[32mSUCCESS 1[0m in 3.36s]
[2025-05-06T03:58:12.743+0000] {subprocess.py:93} INFO - [0m03:58:12  3 of 3 START sql table model analytics.output .................................. [RUN]
[2025-05-06T03:58:15.591+0000] {subprocess.py:93} INFO - [0m03:58:15  3 of 3 OK created sql table model analytics.output ............................. [[32mSUCCESS 1[0m in 2.84s]
[2025-05-06T03:58:15.605+0000] {subprocess.py:93} INFO - [0m03:58:15
[2025-05-06T03:58:15.608+0000] {subprocess.py:93} INFO - [0m03:58:15  Finished running 3 table models in 0 hours 0 minutes and 14.87 seconds (14.87s).
[2025-05-06T03:58:15.777+0000] {subprocess.py:93} INFO - [0m03:58:15
[2025-05-06T03:58:15.779+0000] {subprocess.py:93} INFO - [0m03:58:15  [32mCompleted successfully[0m
[2025-05-06T03:58:15.782+0000] {subprocess.py:93} INFO - [0m03:58:15
[2025-05-06T03:58:15.785+0000] {subprocess.py:93} INFO - [0m03:58:15  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2025-05-06T03:58:17.222+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-06T03:58:17.256+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-06T03:58:17.258+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2025-05-06T03:57:53.262913+00:00, execution_date=20250506T035753, start_date=20250506T035754, end_date=20250506T035817
[2025-05-06T03:58:17.314+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-06T03:58:17.345+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-06T03:58:17.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
